### PR TITLE
Bump rustls version and fix some unwrap usage

### PR DESCRIPTION
**Pull request by w93163red**
update dep to the latest version for updating Keyhouse dependencies

### CODE REVIEW

**Comment by w93163red** [comment]
env_logger did not bump regex version, hence skip the check for now
https://rustsec.org/advisories/RUSTSEC-2022-0013.html

**Comment by dingelish** [comment]
KMSV2 -> keyhouse ty

**Comment by dingelish** [comment]
basically lgtm. please don't forget to squash the commits. @Ruide how do you think

**Comment by w93163red** [comment]
image

the button is ready

**Comment by Ruide** [comment]
> basically lgtm. please don't forget to squash the commits. @Ruide how do you think

Now going through the API changes. so far so good. Would comment once I finish reviewing.

**Review by dingelish — APPROVED** [review]

**Review by Ruide — APPROVED** [review]

**Pull request merged**
